[package]
name = "ai-col"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
toml = "0.5.8"
serde = { version = "1.0.129", features = ["derive"] }